### ISSUE TITLE
Pass reading room request information to request broker

### ISSUE THREAD

**Issue by p-galligan** [RockefellerArchiveCenter/library_project_scripting#15]
**Describe the solution you'd like**
The application should be able to pass necessary retrieval information from existing data to the request broker, and eventually Aeon.

Since all data is coming from GH and not AS, we'll have to pass directly from existing data. Minimum should include title and call number.

**Comment by helrond** [comment]
@p-galligan I'd like to suggest that we bypass the request broker and go directly to Aeon, for the following reasons:
- We already have all the data, and we can't get any more from the request broker since this data is no longer in AS.
- We already know all of these items are requestable.

So instead of hitting the request broker, I think we should just send a POST request directly to Aeon. This will require setting up some hidden inputs in the request modal (see #40) but we can copy our existing implementation. in DIMES for that. Thoughts?

**Comment by p-galligan** [comment]
@helrond I think you're right and this makes sense. That data can be grabbed directly from the json files we already have.
