### ISSUE TITLE
Add all data to development before merging into base

### ISSUE THREAD

**Issue by p-galligan** [RockefellerArchiveCenter/library_project_scripting#53]
**Is your feature request related to a problem? Please describe.**
Development branch is running off of a small set of sample data right now.

**Describe the solution you'd like**
Need to add all data to the `_data` directory before merging into the `base` branch.

**Comment by helrond** [comment]
@p-galligan one thing about this - I think we want to consider whether it makes sense to version the data separately from the site and pull them in using a git submodule. As you can see, I've already gitignored the pages (which are in the `items` directory) in order to cut down on the number of files we're versioning here.

There are advantages and disadvantages either way, but it's worth thinking about.
